### ISSUE TITLE
Define the teams/customers in a CM globally and the values.yaml consumes that CM

### ISSUE THREAD

**Issue by tvalchev2** [newrelic-experimental/monitoring-kubernetes-with-opentelemetry#12]
It would be easier if it was possible for the values.yaml/the collectors to consume a ConfigMap, where the teams/customers are defined in order to enable easier rollout. 
Define the customers for the global config in an external ConfigMap (for example) where the helmchart gets the teams Data from the CM or the collectors mount that CM and use its data to build the definition of customers.

Use case:
We intend to create a CronJob, that is iterating over the namespaces on the cluster, checks if the namespace has a label "customer-id" (for example: customer-id = devteam1) and if it does, then it creates a secret with the correct API-Key for that customer and then creates a formated ConfigMap, which contains all the customer/teams on that cluster.

For Example if we define a ConfigMap like this:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-opentelemetry-teams
  namespace: opentelemetry
data:
  teams: |-
    # teams definition
      devteam1:
        licenseKey:
          secretRef:
            name: "<YOUR_EXISTING_SECRET_DEVTEAM_1>"
            key: "<KEY_TO_LICENSE_KEY_WITHIN_THE_SECRET_DEVTEAM_1>"
        namespaces: []
      devteam2:
        licenseKey:
          secretRef:
            name: "<YOUR_EXISTING_SECRET_DEVTEAM_2>"
            key: "<KEY_TO_LICENSE_KEY_WITHIN_THE_SECRET_DEVTEAM_2>"
        namespaces:
          - namespace-devteam-2
   ............
      devteam70:
        licenseKey:
          secretRef:
            name: "<YOUR_EXISTING_SECRET_DEVTEAM_70>"
            key: "<KEY_TO_LICENSE_KEY_WITHIN_THE_SECRET_DEVTEAM_70>"
        namespaces:
          - namespace-devteam-70
```

Could you make it possible to consume that configmap? So basically in the values.yaml we have something like this instead:

```
global:
  newrelic:
    enabled: true
    endpoint: "OTLP_ENDPOINT_FOR_ALL_ACCOUNTS"
    teams:
      configMapRef:
        name: cm-opentelemetry-teams
        key: teams
```

And then maybe you can set this in the _helpers.tpl that if a configMapRef is defined, then it should get the values for the teams from there. We can test this together. This would help us a lot for the rollout of the Helm Values on all our clusters, since we use MonoRepo principle where we have Flux CD taking care of the deployment and consistency of our infrastructure among a large amount of clusters.
