### ISSUE TITLE
Migrate deprecated memory_ballast extension to GOMEMLIMIT variable.

### ISSUE THREAD

**Issue by sfqzlm** [newrelic-experimental/monitoring-kubernetes-with-opentelemetry#144]
## Summary

Replace deprecated [memory_ballast extension](https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/ballastextension/README.md) with GOMEMLIMIT variable.

The memory ballast extension is deprecated in favor of using the GOMEMLIMIT environment variable. This environment variable is available on any Collector built with Go 1.19 or higher. 

## Desired Behavior

Achieve the same functionality with  GOMEMLIMIT variable.

## Possible Solution

To migrate to  GOMEMLIMIT, set its value to 80% of the hard memory limit of your Collector. For example, if the Collector hard memory limit is 1GiB, set GOMEMLIMIT to 800MiB.

```
env:
      # GOMEMLIMIT variable sets a soft memory limit for the runtime. It should be set to 80% of the hard memory limit of your collector.
    - name: GOMEMLIMIT
      value: 100MiB
```
