### ISSUE TITLE
Provide the possibility to implement drop rules for Logs

### ISSUE THREAD

**Issue by tvalchev2** [newrelic-experimental/monitoring-kubernetes-with-opentelemetry#160]
[NOTE]: # " ^^ Provide a general summary of the request in the title above. ^^ "

## Summary
At the moment we have drop rules at NewRelic to prevent unwanted Logs being ingested and producing Costs. Example of dropped Logs - healthcheck logs from the pods/applciations in the pods and success logs with status Code 200 (for nginx requests for example). However these logs are still getting ingested by opentelemetry and sent to NewRelic Endpoint, producing unneeded Load on the collectors/senders.

[NOTE]: # " Provide a brief overview of what the new feature is all about. "

## Desired Behavior
One should be able to define drop/filtering rules where Logs with certain pattern won't get sent to NewRelic and won't have to be handled by the collector (at least not for sending them)

[NOTE]: # " Tell us how the new feature should work. Be specific. "
[TIP]: # " Do NOT give us access or passwords to your New Relic account or API keys! "

## Possible Solution
This should be possible in my opinion with the filterprocessor, but we need to be able to define those droprules at the HelmChart. In example:
`2024-08-06 11:17:48.550 INFO  (qtp1597328335-63) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/health params={} status=0 QTime=0`
```
processors:
  filter/drop_logs_by_body_regex:
    logs:
      log_record:
        - 'IsMatch(body, ".*path=/admin/info/health.*")'
```
This should drop the HealthChecks for a Solr application running on the cluster (maybe my regex is wrong and one needs to backslash the backslashes, but I guess you get the point). This healthcheck is running every 5 seconds, so it produces a huge amount of logs and Strain on the collector when it has to send like 1000 such log messages every 5 seconds.

Or here a 2nd example for dropping lets say based on an attribute:
```
processors:
  filter/drop_logs_by_label_values_regex:
    logs:
      log_record:
        - IsMatch(attributes["http.method"], "GET|POST")
```

[NOTE]: # " Not required. Suggest how to implement the addition or change. "

## Additional context

[TIP]: # " Why does this feature matter to you? What unique circumstances do you have? "
