### ISSUE TITLE
Fix nr-otel-dep ServiceAccount and ClusterRole not having the proper access to "kube-system" Namespace on the 

### ISSUE THREAD

**Issue by hodor9** [newrelic-experimental/monitoring-kubernetes-with-opentelemetry#50]
[NOTE]: # " ^^ Provide a general summary of the issue in the title above. ^^ "

## Description
The nr-otel-dep-rec-collector throws constantly errors, that it cannot access the "kube-system" Namespace, because it cannot watch and get "namespaces" on the API Group "" at the Cluster scope.

[NOTE]: # " Describe the problem you're encountering. "
[TIP]: # " Do NOT give us access or passwords to your New Relic account or API keys! "

## Steps to Reproduce
Install nrotelk8s Version 0.2.1 with namespaces filter for a team, that has the kube-system Namespace active. Check the nr-otel-dep-rec-collector for the errors. 

[NOTE]: # " Please be as specific as possible. "

## Expected Behavior
The nr-otel-dep ServiceAccount and ClusterRole have the rights to list Namespaces and there are no errors in the nr-otel-dep-rec-collector Pod.
[NOTE]: # " Tell us what you expected to happen. "

## Relevant Logs / Console output
```
W1017 15:03:11.266116       1 reflector.go:535] k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: failed to list *v1.Namespace: namespaces "kube-system" is forbidden: User "system:serviceaccount:opentelemetry:nr-otel-dep" cannot list resource "namespaces" in API group "" at the cluster scope: Azure does not have opinion for this user.
E1017 15:03:11.266157       1 reflector.go:147] k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces "kube-system" is forbidden: User "system:serviceaccount:opentelemetry:nr-otel-dep" cannot list resource "namespaces" in API group "" at the cluster scope: Azure does not have opinion for this user.
```
[NOTE]: # " Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. "

## Your Environment

[TIP]: # " Include as many relevant details about your environment as possible. "

- ex: Your Kubernetes manifest files:
```
global:
  newrelic:
    enabled: true
    endpoint: otlp.eu01.nr-data.net:4317
    teams:
      opsteam:
        licenseKey:              
          secretRef: 
            name: otel-monitoring-keys
            key: opsteam-ingest-key
        namespaces:
        - kube-system
        - flux-system
        - monitoring
        - opentelemetry
        - ingress*
        - default
```
- ex: nrotelk8s Version: 0.2.1

## Additional context
![image](https://github.com/newrelic-experimental/monitoring-kubernetes-with-opentelemetry/assets/101270326/0decf166-c472-4b2f-9d6f-d9b2f6b87cee)
The ClusterRole used by the nr-otel-dep-rec-collector cannot list/get/watch Namespaces on the "" scope.
[TIP]: # " Add any other context about the problem here. "
